In [9]:
import pandas as pd
from numpy import genfromtxt

In [3]:
data=pd.read_csv('train.csv')
data

,id,age,education,sex,is_smoking,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,0,64,2.0,F,YES,3.0,0.0,0,0,0,221.0,148.0,85.0,NaN,90.0,80.0,1
1,1,36,4.0,M,NO,0.0,0.0,0,1,0,212.0,168.0,98.0,29.77,72.0,75.0,0
2,2,46,1.0,F,YES,10.0,0.0,0,0,0,250.0,116.0,71.0,20.35,88.0,94.0,0
3,3,50,1.0,M,YES,20.0,0.0,0,1,0,233.0,158.0,88.0,28.26,68.0,94.0,1
4,4,64,1.0,F,YES,30.0,0.0,0,0,0,241.0,136.5,85.0,26.42,70.0,77.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3385,3385,60,1.0,F,NO,0.0,0.0,0,0,0,261.0,123.5,79.0,29.28,70.0,103.0,0
3386,3386,46,1.0,F,NO,0.0,0.0,0,0,0,199.0,102.0,56.0,21.96,80.0,84.0,0
3387,3387,44,3.0,M,YES,3.0,0.0,0,1,0,352.0,164.0,119.0,28.92,73.0,72.0,1
3388,3388,60,1.0,M,NO,0.0,NaN,0,1,0,191.0,167.0,105.0,23.01,80.0,85.0,0
3389,3389,54,3.0,F,NO,0.0,0.0,0,0,0,288.0,124.0,77.0,29.88,79.0,92.0,0

In [4]:
dv = data.values

In [5]:
type(dv)

numpy.ndarray

In [6]:
X = [d[:-1] for d in dv]
y = [d[-1] for d in dv]

In [7]:
X

[array([0, 64, 2.0, 'F', 'YES', 3.0, 0.0, 0, 0, 0, 221.0, 148.0, 85.0, nan,
        90.0, 80.0], dtype=object),
 array([1, 36, 4.0, 'M', 'NO', 0.0, 0.0, 0, 1, 0, 212.0, 168.0, 98.0,
        29.77, 72.0, 75.0], dtype=object),
 array([2, 46, 1.0, 'F', 'YES', 10.0, 0.0, 0, 0, 0, 250.0, 116.0, 71.0,
        20.35, 88.0, 94.0], dtype=object),
 array([3, 50, 1.0, 'M', 'YES', 20.0, 0.0, 0, 1, 0, 233.0, 158.0, 88.0,
        28.26, 68.0, 94.0], dtype=object),
 array([4, 64, 1.0, 'F', 'YES', 30.0, 0.0, 0, 0, 0, 241.0, 136.5, 85.0,
        26.42, 70.0, 77.0], dtype=object),
 array([5, 61, 3.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 272.0, 182.0, 121.0,
        32.8, 85.0, 65.0], dtype=object),
 array([6, 61, 1.0, 'M', 'NO', 0.0, 0.0, 0, 1, 0, 238.0, 232.0, 136.0,
        24.83, 75.0, 79.0], dtype=object),
 array([7, 36, 4.0, 'M', 'YES', 35.0, 0.0, 0, 0, 0, 295.0, 102.0, 68.0,
        28.15, 60.0, 63.0], dtype=object),
 array([8, 41, 2.0, 'F', 'YES', 20.0, nan, 0, 0, 0, 220.0, 126.0, 78.0,
        20.7, 86.0, 79.0], dtype=object),
 array([9, 55, 2.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 326.0, 144.0, 81.0,
        25.71, 85.0, nan], dtype=object),
 array([10, 61, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, nan, 185.0, 121.0,
        35.22, 80.0, nan], dtype=object),
 array([11, 53, 2.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 210.0, 138.0, 86.5,
        22.49, 88.0, 87.0], dtype=object),
 array([12, 43, 2.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 213.0, 96.0, 62.0,
        19.38, 74.0, 80.0], dtype=object),
 array([13, 44, 1.0, 'M', 'YES', 40.0, 0.0, 0, 0, 0, 227.0, 146.5, 97.0,
        26.92, 80.0, 67.0], dtype=object),
 array([14, 58, 3.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 188.0, 160.0, 120.0,
        35.58, 88.0, 85.0], dtype=object),
 array([15, 51, 1.0, 'M', 'YES', 15.0, 0.0, 0, 0, 0, 212.0, 146.0, 89.0,
        24.49, 100.0, 132.0], dtype=object),
 array([16, 50, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 240.0, 163.0, 105.0,
        31.37, 89.0, 75.0], dtype=object),
 array([17, 44, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 257.0, 129.0, 93.0,
        27.56, 75.0, 76.0], dtype=object),
 array([18, 56, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 267.0, 122.5, 85.0,
        24.22, 92.0, 100.0], dtype=object),
 array([19, 42, 1.0, 'M', 'YES', 30.0, 0.0, 0, 0, 0, 232.0, 130.0, 91.0,
        25.77, 72.0, 70.0], dtype=object),
 array([20, 42, 1.0, 'F', 'YES', 20.0, 0.0, 0, 1, 0, 199.0, 141.0, 92.0,
        43.69, 80.0, 60.0], dtype=object),
 array([21, 38, 2.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 175.0, 142.0, 86.0,
        22.01, 82.0, 73.0], dtype=object),
 array([22, 38, 1.0, 'F', 'YES', 30.0, 0.0, 0, 0, 0, 164.0, 113.0, 68.0,
        25.75, 70.0, 75.0], dtype=object),
 array([23, 63, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 226.0, 172.5, 98.0,
        26.47, 87.0, 81.0], dtype=object),
 array([24, 35, 2.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 248.0, 107.0, 73.0,
        20.64, 90.0, 80.0], dtype=object),
 array([25, 44, 1.0, 'M', 'YES', 10.0, 0.0, 0, 0, 0, 220.0, 105.0, 70.0,
        21.01, 58.0, 68.0], dtype=object),
 array([26, 36, 3.0, 'M', 'YES', 15.0, 0.0, 0, 0, 0, 245.0, 122.0, 74.5,
        24.27, 79.0, 85.0], dtype=object),
 array([27, 54, 2.0, 'M', 'YES', 3.0, 0.0, 0, 1, 0, 279.0, 155.0, 105.0,
        26.47, 78.0, 66.0], dtype=object),
 array([28, 41, 2.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 245.0, 134.0, 98.0,
        24.26, 85.0, 78.0], dtype=object),
 array([29, 63, 1.0, 'F', 'NO', 0.0, 0.0, 1, 1, 0, 273.0, 152.0, 70.0,
        19.69, 80.0, 79.0], dtype=object),
 array([30, 51, 2.0, 'M', 'NO', 0.0, 0.0, 0, 1, 0, 227.0, 158.0, 105.0,
        27.22, 60.0, 96.0], dtype=object),
 array([31, 55, 3.0, 'M', 'YES', 20.0, 0.0, 0, 1, 0, 252.0, 129.0, 84.0,
        23.55, 80.0, 72.0], dtype=object),
 array([32, 51, 3.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 198.0, 142.5, 80.0,
        23.86, 76.0, 100.0], dtype=object),
 array([33, 38, 2.0, 'M', 'YES', 30.0, 0.0, 0, 1, 0, 266.0, 149.0, 91.0,
        31.08, 69.0, 61.0], dtype=object),
 array([34, 62, 1.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 216.0, 126.0, 82.0,
        21.18, 69.0, 69.0], dtype=object),
 array([35, 47, 2.0, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 237.0, 130.0, 78.0,
        19.66, 80.0, 75.0], dtype=object),
 array([36, 46, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 193.0, 106.5, 70.5,
        26.18, 75.0, nan], dtype=object),
 array([37, 63, 2.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 293.0, 186.5, 97.0,
        30.47, 60.0, 96.0], dtype=object),
 array([38, 41, 2.0, 'F', 'YES', 9.0, 1.0, 1, 1, 0, 180.0, 114.0, 70.0,
        22.41, 92.0, nan], dtype=object),
 array([39, 43, 3.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 237.0, 104.0, 74.0,
        23.02, 60.0, 77.0], dtype=object),
 array([40, 34, 3.0, 'F', 'YES', 10.0, 0.0, 0, 0, 0, 206.0, 101.0, 63.0,
        21.5, 75.0, 66.0], dtype=object),
 array([41, 51, 4.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 199.0, 113.0, 68.0,
        22.46, 58.0, 68.0], dtype=object),
 array([42, 39, 1.0, 'M', 'YES', 60.0, 0.0, 0, 0, 0, 215.0, 112.0, 65.0,
        23.6, 59.0, 78.0], dtype=object),
 array([43, 46, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 208.0, 122.0, 76.0,
        18.4, 75.0, 70.0], dtype=object),
 array([44, 51, 1.0, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 262.0, 102.0, 64.0,
        28.06, 80.0, 66.0], dtype=object),
 array([45, 64, 3.0, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 270.0, 142.0, 68.0,
        21.32, 76.0, 80.0], dtype=object),
 array([46, 55, 2.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 293.0, 165.0, 106.0,
        24.71, 90.0, 79.0], dtype=object),
 array([47, 59, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 292.0, 114.0, 84.0,
        27.39, 68.0, 72.0], dtype=object),
 array([48, 55, 1.0, 'F', 'YES', 10.0, 0.0, 0, 0, 0, 346.0, 131.0, 81.0,
        22.69, 75.0, 77.0], dtype=object),
 array([49, 46, nan, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 212.0, 122.5, 75.5,
        23.51, 67.0, 103.0], dtype=object),
 array([50, 62, 3.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 202.0, 111.0, 79.5,
        27.91, 80.0, 100.0], dtype=object),
 array([51, 56, 3.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 340.0, 134.0, 89.5,
        21.91, 50.0, 72.0], dtype=object),
 array([52, 45, 2.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 262.0, 133.0, 83.0,
        22.19, 76.0, 92.0], dtype=object),
 array([53, 44, 1.0, 'M', 'YES', 30.0, 0.0, 0, 0, 0, 334.0, 131.0, 74.0,
        28.82, 80.0, 77.0], dtype=object),
 array([54, 63, 1.0, 'M', 'YES', 20.0, 0.0, 1, 1, 0, 213.0, 163.0, 94.0,
        nan, 76.0, 69.0], dtype=object),
 array([55, 51, 2.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 351.0, 134.0, 97.5,
        21.66, 100.0, nan], dtype=object),
 array([56, 49, 1.0, 'F', 'YES', 9.0, 0.0, 0, 0, 0, 235.0, 109.0, 70.0,
        28.66, 74.0, 73.0], dtype=object),
 array([57, 55, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 243.0, 142.0, 92.0,
        30.24, 70.0, 85.0], dtype=object),
 array([58, 46, 3.0, 'F', 'YES', 30.0, 0.0, 0, 0, 0, 196.0, 114.0, 75.0,
        21.01, 60.0, 69.0], dtype=object),
 array([59, 60, 3.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 275.0, 141.0, 84.0,
        29.66, 75.0, 105.0], dtype=object),
 array([60, 38, 2.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 186.0, 105.0, 57.0,
        21.1, 85.0, 68.0], dtype=object),
 array([61, 40, 2.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 190.0, 121.5, 74.5,
        29.35, 73.0, 93.0], dtype=object),
 array([62, 52, nan, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 268.0, 109.0, 70.0,
        23.74, 75.0, 78.0], dtype=object),
 array([63, 48, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 234.0, 144.0, 90.0,
        29.34, 72.0, 70.0], dtype=object),
 array([64, 62, 2.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 264.0, 129.0, 85.0,
        26.15, 73.0, 63.0], dtype=object),
 array([65, 37, 4.0, 'F', 'YES', 10.0, 0.0, 0, 0, 0, 156.0, 120.0, 87.0,
        21.8, 66.0, 89.0], dtype=object),
 array([66, 60, 2.0, 'M', 'YES', 20.0, 0.0, 0, 1, 0, 260.0, 178.0, 103.0,
        24.62, 72.0, 79.0], dtype=object),
 array([67, 60, 1.0, 'M', 'NO', 0.0, 0.0, 0, 1, 0, 225.0, 149.0, 96.0,
        27.73, 80.0, 60.0], dtype=object),
 array([68, 61, 2.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 183.0, 150.0, 86.0,
        25.05, 66.0, 70.0], dtype=object),
 array([69, 65, nan, 'M', 'NO', 0.0, 0.0, 0, 0, 0, nan, 152.5, 97.5, 28.35,
        65.0, 73.0], dtype=object),
 array([70, 50, 3.0, 'M', 'YES', 30.0, 0.0, 0, 0, 0, 210.0, 121.5, 78.0,
        26.29, 88.0, 77.0], dtype=object),
 array([71, 63, 1.0, 'M', 'NO', 0.0, 0.0, 0, 1, 0, 246.0, 193.0, 104.0,
        23.08, 80.0, 73.0], dtype=object),
 array([72, 42, 1.0, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 237.0, 105.0, 75.0,
        23.85, 70.0, 87.0], dtype=object),
 array([73, 58, 4.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 268.0, 151.0, 98.0,
        20.34, 72.0, 60.0], dtype=object),
 array([74, 36, 3.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 174.0, 131.0, 86.0,
        26.23, 75.0, 64.0], dtype=object),
 array([75, 62, 4.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 288.0, 118.5, 71.0,
        26.18, 68.0, 87.0], dtype=object),
 array([76, 37, 4.0, 'M', 'YES', 60.0, 0.0, 0, 0, 0, 254.0, 122.5, 82.5,
        23.87, 88.0, 83.0], dtype=object),
 array([77, 63, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 1, 150.0, 152.0, 88.0,
        36.54, 72.0, 170.0], dtype=object),
 array([78, 52, 1.0, 'M', 'YES', 20.0, 0.0, 0, 1, 0, 232.0, 155.0, 80.5,
        29.6, 72.0, 67.0], dtype=object),
 array([79, 57, 1.0, 'M', 'YES', 30.0, 0.0, 0, 0, 0, 211.0, 122.0, 66.5,
        20.19, 62.0, 57.0], dtype=object),
 array([80, 40, 4.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 161.0, 122.0, 85.0,
        30.8, 75.0, 85.0], dtype=object),
 array([81, 41, 4.0, 'M', 'YES', 40.0, 0.0, 0, 0, 0, 254.0, 141.0, 100.0,
        27.68, 110.0, nan], dtype=object),
 array([82, 48, 2.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 274.0, 134.0, 84.0,
        31.78, 85.0, 80.0], dtype=object),
 array([83, 51, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 226.0, 105.0, 71.0,
        27.73, 68.0, 79.0], dtype=object),
 array([84, 41, 2.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 237.0, 125.0, 83.0,
        24.56, 73.0, 61.0], dtype=object),
 array([85, 46, 2.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 214.0, 110.0, 73.0,
        18.1, 60.0, 60.0], dtype=object),
 array([86, 52, 2.0, 'M', 'NO', 0.0, 0.0, 1, 0, 0, 202.0, 136.0, 94.0,
        29.93, 83.0, 67.0], dtype=object),
 array([87, 64, 1.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 232.0, 113.5, 70.0,
        21.03, 80.0, 58.0], dtype=object),
 array([88, 41, 2.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 180.0, 127.0, 86.0,
        20.72, 73.0, 63.0], dtype=object),
 array([89, 61, 1.0, 'M', 'NO', 0.0, 0.0, 0, 1, 0, 243.0, 142.0, 89.0,
        27.3, 65.0, 67.0], dtype=object),
 array([90, 51, 1.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 195.0, 122.0, 72.0,
        21.51, 82.0, 64.0], dtype=object),
 array([91, 51, 3.0, 'F', 'YES', 15.0, 0.0, 0, 1, 0, 275.0, 150.0, 99.0,
        23.17, 75.0, 65.0], dtype=object),
 array([92, 36, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 165.0, 115.0, 71.0,
        21.27, 64.0, 86.0], dtype=object),
 array([93, 40, 3.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 248.0, 136.5, 78.0,
        24.6, 90.0, 99.0], dtype=object),
 array([94, 52, 4.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 302.0, 110.0, 67.5,
        23.51, 63.0, 87.0], dtype=object),
 array([95, 40, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 240.0, 108.0, 72.0,
        17.64, 78.0, nan], dtype=object),
 array([96, 49, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 265.0, 150.0, 77.5,
        21.83, 96.0, 107.0], dtype=object),
 array([97, 42, 3.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 235.0, 103.0, 70.0,
        21.48, 67.0, 73.0], dtype=object),
 array([98, 41, 4.0, 'M', 'NO', 0.0, 0.0, 0, 1, 0, 206.0, 124.0, 90.0,
        30.69, 75.0, 83.0], dtype=object),
 array([99, 58, 1.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 251.0, 135.0, 85.5,
        21.24, 88.0, 103.0], dtype=object),
 array([100, 47, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 205.0, 133.0, 93.0,
        27.82, 68.0, 60.0], dtype=object),
 array([101, 42, 2.0, 'M', 'YES', 30.0, 0.0, 0, 0, 0, 209.0, 130.0, 86.0,
        24.01, 60.0, 55.0], dtype=object),
 array([102, 68, 2.0, 'F', 'NO', 0.0, nan, 0, 0, 0, 257.0, 144.0, 95.0,
        29.25, 80.0, 77.0], dtype=object),
 array([103, 48, 2.0, 'M', 'YES', 20.0, 0.0, 0, 1, 0, 258.0, 150.0, 105.0,
        25.94, 83.0, 60.0], dtype=object),
 array([104, 57, nan, 'F', 'NO', 0.0, 1.0, 0, 1, 0, 190.0, 155.0, 85.0,
        26.08, 55.0, 66.0], dtype=object),
 array([105, 60, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 222.0, 118.0, 73.0,
        24.48, 75.0, 90.0], dtype=object),
 array([106, 46, 3.0, 'F', 'YES', 15.0, 0.0, 0, 0, 0, 247.0, 125.0, 80.0,
        21.51, 60.0, 80.0], dtype=object),
 array([107, 45, 4.0, 'M', 'NO', 0.0, 0.0, 0, 0, 1, 189.0, 132.0, 78.0,
        28.4, 75.0, 177.0], dtype=object),
 array([108, 49, 1.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 288.0, 128.0, 89.0,
        35.96, 73.0, 75.0], dtype=object),
 array([109, 42, 1.0, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 173.0, 100.0, 63.0,
        23.25, 65.0, 99.0], dtype=object),
 array([110, 42, 2.0, 'F', 'YES', 9.0, 0.0, 0, 0, 0, 281.0, 115.5, 79.0,
        22.9, 80.0, 71.0], dtype=object),
 array([111, 45, 2.0, 'F', 'YES', 3.0, 0.0, 0, 0, 0, 250.0, 130.0, 80.0,
        20.24, 90.0, 86.0], dtype=object),
 array([112, 57, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 382.0, 133.0, 77.0,
        24.27, 75.0, 81.0], dtype=object),
 array([113, 41, 1.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 181.0, 125.0, 79.0,
        19.09, 60.0, 70.0], dtype=object),
 array([114, 40, 4.0, 'F', 'YES', 10.0, 0.0, 0, 0, 0, 200.0, 116.0, 69.0,
        23.9, 75.0, 78.0], dtype=object),
 array([115, 52, 2.0, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 244.0, 127.5, 72.5,
        24.29, 67.0, 118.0], dtype=object),
 array([116, 39, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 213.0, 125.0, 87.0,
        16.73, 110.0, 75.0], dtype=object),
 array([117, 45, 2.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 232.0, 122.5, 82.5,
        27.55, 74.0, 59.0], dtype=object),
 array([118, 48, 2.0, 'M', 'YES', 17.0, 0.0, 0, 0, 0, 218.0, 113.0, 79.0,
        27.33, 62.0, 73.0], dtype=object),
 array([119, 64, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 213.0, 133.0, 77.5,
        35.62, 77.0, 74.0], dtype=object),
 array([120, 65, nan, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 221.0, 155.0, 92.0,
        31.34, 58.0, nan], dtype=object),
 array([121, 64, 4.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 273.0, 123.0, 73.5,
        22.3, 75.0, 84.0], dtype=object),
 array([122, 61, 2.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 270.0, 174.5, 101.5,
        29.87, 80.0, 76.0], dtype=object),
 array([123, 36, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 188.0, 112.0, 78.0,
        22.54, 63.0, 73.0], dtype=object),
 array([124, 45, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 195.0, 129.5, 83.0,
        25.74, 77.0, 74.0], dtype=object),
 array([125, 60, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 266.0, 135.0, 87.0,
        26.72, 75.0, 82.0], dtype=object),
 array([126, 45, 1.0, 'M', 'YES', 25.0, 0.0, 0, 1, 0, 232.0, 165.0, 86.0,
        23.86, 78.0, 68.0], dtype=object),
 array([127, 57, 2.0, 'M', 'YES', 15.0, 0.0, 0, 0, 0, 221.0, 117.0, 72.0,
        25.51, 75.0, 83.0], dtype=object),
 array([128, 67, 2.0, 'F', 'NO', 0.0, nan, 0, 0, 0, 261.0, 117.0, 63.0,
        22.55, 75.0, 83.0], dtype=object),
 array([129, 62, 2.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 214.0, 110.0, 62.5,
        23.8, 77.0, 95.0], dtype=object),
 array([130, 63, 1.0, 'M', 'NO', 0.0, 0.0, 0, 0, 1, 229.0, 109.0, 75.0,
        38.42, 110.0, 120.0], dtype=object),
 array([131, 47, 2.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 200.0, 126.0, 86.0,
        26.84, 80.0, 96.0], dtype=object),
 array([132, 48, 1.0, 'F', 'YES', 10.0, 0.0, 0, 1, 0, 268.0, 117.5, 80.0,
        36.11, 72.0, 67.0], dtype=object),
 array([133, 61, nan, 'M', 'YES', 5.0, 0.0, 0, 0, 0, 175.0, 134.0, 82.5,
        18.59, 72.0, 75.0], dtype=object),
 array([134, 64, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 1, 262.0, 147.0, 90.0,
        26.51, 85.0, 173.0], dtype=object),
 array([135, 63, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 235.0, 125.0, 79.0,
        24.38, 96.0, 83.0], dtype=object),
 array([136, 38, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 174.0, 101.0, 68.0,
        27.47, 85.0, nan], dtype=object),
 array([137, 39, 1.0, 'M', 'YES', 43.0, 0.0, 0, 1, 0, 291.0, 177.5, 100.0,
        25.74, 67.0, 91.0], dtype=object),
 array([138, 53, 3.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 238.0, 172.5, 91.0,
        24.16, 112.0, nan], dtype=object),
 array([139, 50, 2.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 312.0, 125.0, 85.0,
        27.07, 88.0, 94.0], dtype=object),
 array([140, 45, 1.0, 'F', 'YES', 5.0, 0.0, 0, 0, 0, 170.0, 109.5, 69.0,
        17.38, 88.0, 66.0], dtype=object),
 array([141, 57, 1.0, 'M', 'NO', 0.0, 0.0, 0, 1, 0, 176.0, 134.0, 97.0,
        38.14, 68.0, 94.0], dtype=object),
 array([142, 67, 2.0, 'F', 'YES', 3.0, 0.0, 0, 1, 0, 326.0, 157.5, 78.0,
        24.63, 85.0, 77.0], dtype=object),
 array([143, 55, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 257.0, 132.0, 81.0,
        27.49, 60.0, 86.0], dtype=object),
 array([144, 46, 1.0, 'F', 'YES', 3.0, 0.0, 0, 0, 0, 193.0, 118.0, 92.0,
        21.14, 75.0, 78.0], dtype=object),
 array([145, 40, 1.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 290.0, 120.0, 89.0,
        27.99, 80.0, 66.0], dtype=object),
 array([146, 42, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 204.0, 108.0, 70.5,
        27.71, 75.0, 65.0], dtype=object),
 array([147, 61, 1.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 227.0, 130.0, 77.5,
        26.18, 63.0, 91.0], dtype=object),
 array([148, 55, 1.0, 'M', 'YES', 30.0, 0.0, 0, 1, 0, 239.0, 144.0, 96.5,
        28.82, 70.0, 102.0], dtype=object),
 array([149, 41, 1.0, 'M', 'YES', 30.0, 0.0, 0, 0, 0, 198.0, 106.0, 71.0,
        21.51, 85.0, 84.0], dtype=object),
 array([150, 43, 1.0, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 245.0, 112.5, 80.0,
        23.43, 90.0, 77.0], dtype=object),
 array([151, 52, 3.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 265.0, 106.0, 79.0,
        26.48, 80.0, 163.0], dtype=object),
 array([152, 38, 1.0, 'F', 'YES', 15.0, 0.0, 0, 0, 0, 199.0, 112.0, 68.5,
        23.88, 85.0, 67.0], dtype=object),
 array([153, 38, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 162.0, 105.0, 70.0,
        21.35, 72.0, 71.0], dtype=object),
 array([154, 49, 1.0, 'M', 'YES', 30.0, 0.0, 0, 0, 0, 199.0, 107.5, 71.0,
        26.62, 70.0, 68.0], dtype=object),
 array([155, 41, 2.0, 'M', 'YES', 20.0, 0.0, 0, 0, 0, 260.0, 120.0, 72.5,
        26.36, 73.0, 88.0], dtype=object),
 array([156, 39, 2.0, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 190.0, 137.0, 81.0,
        19.57, 80.0, 85.0], dtype=object),
 array([157, 57, 3.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 314.0, 109.5, 72.0,
        25.62, 72.0, 71.0], dtype=object),
 array([158, 48, 2.0, 'M', 'YES', 10.0, 0.0, 0, 0, 0, 260.0, 124.5, 75.5,
        20.42, 68.0, 85.0], dtype=object),
 array([159, 60, 3.0, 'F', 'YES', 3.0, 0.0, 0, 0, 0, 270.0, 130.0, 72.5,
        20.84, 75.0, 102.0], dtype=object),
 array([160, 65, 1.0, 'M', 'YES', 3.0, 0.0, 0, 0, 0, 194.0, 122.0, 68.0,
        26.08, 60.0, 73.0], dtype=object),
 array([161, 61, 1.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 271.0, 133.0, 83.0,
        25.31, 90.0, 60.0], dtype=object),
 array([162, 48, 2.0, 'F', 'YES', 20.0, 0.0, 0, 0, 0, 246.0, 113.0, 87.0,
        18.01, 60.0, 63.0], dtype=object),
 array([163, 67, 1.0, 'F', 'NO', 0.0, 1.0, 0, 1, 0, 251.0, 192.0, 102.0,
        44.09, 55.0, 62.0], dtype=object),
 array([164, 41, 2.0, 'M', 'YES', 40.0, 0.0, 0, 1, 0, 313.0, 114.0, 79.0,
        25.63, 60.0, 93.0], dtype=object),
 array([165, 48, 1.0, 'F', 'YES', 30.0, 0.0, 0, 0, 0, 305.0, 118.5, 73.0,
        20.99, 70.0, 84.0], dtype=object),
 array([166, 53, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 272.0, 165.0, 95.0,
        28.92, 100.0, 100.0], dtype=object),
 array([167, 43, 2.0, 'M', 'NO', 0.0, 0.0, 0, 1, 0, 285.0, 129.0, 95.0,
        26.64, 60.0, 74.0], dtype=object),
 array([168, 61, 4.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 235.0, 207.0, 122.5,
        31.64, 80.0, 72.0], dtype=object),
 array([169, 41, 2.0, 'F', 'YES', 10.0, 0.0, 0, 0, 0, 169.0, 119.0, 72.0,
        19.78, 60.0, 74.0], dtype=object),
 array([170, 41, 3.0, 'F', 'NO', 0.0, 0.0, 0, 0, 0, 180.0, 124.0, 75.5,
        24.2, 68.0, nan], dtype=object),
 array([171, 65, 1.0, 'F', 'NO', 0.0, 0.0, 0, 1, 0, 252.0, 179.5, 114.0,
        30.47, 90.0, 87.0], dtype=object),
 array([172, 38, 2.0, 'M', 'NO', 0.0, 0.0, 0, 0, 0, 150.0, 109.0, 75.0,
        21.43, 64.0, 67.0], dtype=object),

In [8]:
y

[1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 ...]

In [15]:
type(X)

list